from ionlab.IonicEquilibrium.db.matter import Compound

HCl = Compound(cation='H+', anion='Cl-', cation_count=1, anion_count=1)
HNO3 = Compound(cation='H+', anion='NO3-', cation_count=1, anion_count=1)
HF = Compound(cation='H+', anion='F-', cation_count=1, anion_count=1)
Na3PO4 = Compound(cation='Na+', anion='PO43-', cation_count=3, anion_count=1)
Na2HPO4 = Compound(cation='Na+', anion='HPO42-', cation_count=2, anion_count=1)
NaH2PO4 = Compound(cation='Na+', anion='H2PO4-', cation_count=1, anion_count=1)
BaOH2 = Compound(cation='Ba2+', anion='OH-', cation_count=1, anion_count=2)
NaOH = Compound(cation='Na+', anion='OH-', cation_count=1, anion_count=1)
HCOOH = Compound(formula='HCOOH', cation_count=1, anion_count=1)
NH4Cl = Compound(cation='NH4+', anion='Cl-', cation_count=1, anion_count=1)
CH3COOH = Compound(cation='H+', anion='CH3COO-', cation_count=1, anion_count=1)
NaNO2 = Compound(cation='Na+', anion='NO2-', cation_count=1, anion_count=1)
HCN = Compound(cation='H+', anion='CN-', cation_count=1, anion_count=1)
KCN = Compound(cation='K+', anion='CN-', cation_count=1, anion_count=1)
H2SO4 = Compound(formula='H2SO4', cation_count=2, anion_count=1)
HClO4 = Compound(formula='HClO4', cation_count=1, anion_count=1)
NaCN = Compound(cation='Na+', anion='CN-', cation_count=1, anion_count=1)
NaHS = Compound(cation='Na+', anion='HSO3-', cation_count=1, anion_count=1)
HBr = Compound(cation='H+', anion='Br-', cation_count=1, anion_count=1)
NaCl = Compound(cation='Na+', anion='Cl-', cation_count=1, anion_count=1)
BaCl2 = Compound(cation='Ba2+', anion='Cl-', cation_count=1, anion_count=2)
Na2CO3 = Compound(cation='Na+', anion='CO32-', cation_count=2, anion_count=1)
NH2OH = Compound(formula='NH2OH')
CH3NH3Cl = Compound(cation='CH3NH3+', anion='Cl-', cation_count=1, anion_count=1)
NH3 = Compound(formula='NH3')
KBr = Compound('K+', 'Br-', 1, 1)
KOH = Compound(cation='K+', anion='OH-', cation_count=1, anion_count=1)
Cr2SO43 = Compound(cation='Cr3+', anion='SO42-', cation_count=2, anion_count=3)
K2Cr2O7 = Compound(cation='K+', anion='Cr2O72-', cation_count=2, anion_count=1)
CdBr2 = Compound(cation='Cd2+', anion='Br-', cation_count=1, anion_count=2)